### ISSUE TITLE
Can not build using Java 8 and the Jack toolchain

### ISSUE THREAD

**Issue by nunocastro** [HujiangTechnology/gradle_plugin_android_aspectjx#11]
While using the aspectjx plugin, when I set the compile options to Java 8 and enable the jack toolchain, 
` android {
    compileSdkVersion 24
    buildToolsVersion "24.0.1"

```
defaultConfig {
    jackOptions {
        enabled true
    }
}
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

}
`

the build fails with the error:

`Error:Cannot cast object 'task ':app:transformJackWithJackForDebug'' with class 'com.android.build.gradle.internal.pipeline.TransformTask_Decorated' to class 'org.gradle.api.tasks.compile.JavaCompile'`

Using:
- Android Studio 2.2
- Gradle 2.14.1
- Gradle Plugin 2.2

**Comment by firefly1126** [comment]
aspectjx 1.0.8 can work by using Gradle Plugin 2.2.+ and java8,
but not effect on Jack toolchain, because aspectjx depends on the generated intermediate class files and Jack does not generate intermediate class files when compiling an app.

you can known more in https://developer.android.com/guide/platform/j8-jack.html

I will try to solve this problem in the future.

**Comment by YangJing96** [comment]
how did you solve this problem ? I meet this problem too.
